services:
  minio:
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal
    environment:
      MINIO_ROOT_USER: ${COMPUTE_S3_ACCESS_TOKEN}
      MINIO_ROOT_PASSWORD: ${COMPUTE_S3_SECRET_KEY}

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - internal
    environment:
      MINIO_USER: ${COMPUTE_S3_ACCESS_TOKEN?required}
      MINIO_PASS: ${COMPUTE_S3_SECRET_KEY?required}
      MINIO_BUCKET: ${COMPUTE_S3_BUCKET?required}
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set minioc http://minio:9000 $$MINIO_USER $$MINIO_PASS;
      /usr/bin/mc mb minioc/$$MINIO_BUCKET;
      /usr/bin/mc policy set public minioc/$$MINIO_BUCKET;
      exit 0;
      "

  rserve:
    image: veupathdb/rserve:${RSERVE_TAG:-latest}

  email-spoof:
    image: reachfive/fake-smtp-server
    ports:
      - 25:1025
      - 1080:1080
  
  eda-compute:
    depends_on:
      - minio
      - minio-create-buckets
    ports:
      - "8080:8080"

  compute-queue:
    ports:
      - "9002:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${COMPUTE_QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${COMPUTE_QUEUE_PASS}

  compute-queue-db:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"

networks:
  monitoring-ext:
  internal: