version: "3.5"

services:
  data:
    build:
      dockerfile: Dockerfile
      context: ../EdaDataService
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
