version: "3.5"

services:
  user:
    build:
      dockerfile: Dockerfile
      context: ../EdaUserService
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
